services:
  # Gecombineerde web service (Express backend met React frontend)
  - type: web
    name: mymadrassa
    runtime: node
    rootDir: .
    buildCommand: |
      # Verwijder conflicterende bestanden met verschillende hoofdletters
      if [ -f client/src/components/layout/sidebar.tsx ] && [ -f client/src/components/layout/Sidebar.tsx ]; then
        rm client/src/components/layout/sidebar.tsx
      fi
      if [ -f client/src/components/layout/header.tsx ] && [ -f client/src/components/layout/Header.tsx ]; then
        rm client/src/components/layout/header.tsx
      fi
      # Fix problematische bestanden
      cat > client/src/hooks/use-sidebar.ts << 'EOF'
      import { createContext, useContext, useState, ReactNode } from 'react';
      
      type SidebarContextType = {
        isOpen: boolean;
        toggle: () => void;
        close: () => void;
        open: () => void;
      };
      
      const SidebarContext = createContext<SidebarContextType | undefined>(undefined);
      
      export function SidebarProvider({ children }: { children: ReactNode }) {
        const [isOpen, setIsOpen] = useState(
          window.innerWidth >= 768 // Default open on larger screens
        );
      
        const toggle = () => setIsOpen(!isOpen);
        const close = () => setIsOpen(false);
        const open = () => setIsOpen(true);
      
        return (
          <SidebarContext.Provider value={{ isOpen, toggle, close, open }}>
            {children}
          </SidebarContext.Provider>
        );
      }
      
      export default function useSidebar() {
        const context = useContext(SidebarContext);
        if (context === undefined) {
          throw new Error('useSidebar must be used within a SidebarProvider');
        }
        return context;
      }
      EOF
      # Start de normale build
      npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: mymadrassa-db
    databaseName: madrassa
    user: madrassa_user